### ISSUE TITLE
Sign up from startpage

### ISSUE THREAD

**Issue by HelloLudger** [sebsoftnl/moodle-block_coupon#13]
Is it possible to put the sign up form not into the side bar but directly on the startpage?

**Comment by rogiervandongen** [comment]
@HelloLudger 
Please keep an eye on this repository and new repositories that have to do with "coupon".
We're in the process of adding multiple other plugins so life can be made easier.

This will include:
- auth_coupon (allowing for default signup processes with coupon code. It's a simple extend to the default "email" auth module)
- filter_couponinput (allow a coupon input form everywhere filtering can be applied)
- profilefield_coupon (allow a coupon field in user detail form. It's not a real field, but processes any entered/valid coupon code. This can be used in case auth_coupon can't be used for whatever reason)

I think what you may be looking for would be the filter implementation (I'm assuming by "signup form" you actually mean coupon input/validation form).
