### ISSUE TITLE
Claimed by - col is empty after update to Moodle Workplace 4.1.1+ (Build: 20230130) (Moodle 4.1.1 (Build: 20230116))

### ISSUE THREAD

**Issue by neeesn** [sebsoftnl/moodle-block_coupon#15]
Thank you for a good plugin.

Theres an isse after update, that the data is gone.
There is an userid in the database and a link is generated, but it is empty:
![claimed-by-empty](https://user-images.githubusercontent.com/1931926/235637912-5e2e3ea0-f349-4aea-8693-4ccc847b8cff.png)

The link is there and it points to a userprofile, but the <a> Tag is empty.
This is a critical bug, since you cannot see who has claimed the coupon.

**Comment by neeesn** [comment]
We have version 4.2.1 (build 2022090100) installed on the moodle.

**Comment by frederikmillingpytlick** [comment]
See:
https://github.com/sebsoftnl/moodle-block_coupon/pull/17

**Comment by rogiervandongen** [comment]
Is/will be fixed in the next release (coming very soon).
