### ISSUE TITLE
Deprecation warning of block_coupon::$version log

### ISSUE THREAD

**Issue by ryanjbudhu** [sebsoftnl/moodle-block_coupon#25]
[Line 48 in block_coupon.php](https://github.com/sebsoftnl/moodle-block_coupon/blob/811a1b4474769458bbad863befc2957a78946ed7/block_coupon.php#L48) is causing the following error to be logged:
```
 PHP Deprecated:  Creation of dynamic property block_coupon::$version is deprecated in /var/www/moodle/web/blocks/coupon/block_coupon.php on line 48
```
It is only logged when accessing the /admin/ pages in Moodle but weirdly I only noticed it in my most recent update to Moodle 4.4.1. Version and cron info was moved to version.php in 2010 so I don't know how this wasn't caught earlier.

**Comment by rogiervandongen** [comment]
@ryanjbudhu 
As you may have seen from your Pull Request, this will be fixed in the next version of the plugin (I've incorporated the change already, we just need to do a rollout).
