### ISSUE TITLE
Not possible to confirm account with self-registration auth method disabled

### ISSUE THREAD

**Issue by ranver** [sebsoftnl/moodle-block_coupon#4]
After creating an account it's not possible to confirm the account when self-registration is turned off. You cannot turn this on while the self-registration authentication plugin is disabled.

 can_confirm() as returning true isn't implemented in the coupon plugin.

See
https://docs.moodle.org/310/en/error/moodle/confirmationnotenabled

**Comment by rogiervandongen** [comment]
A change is/was made to force "email" as the default signup.
E.g.: when no auth was set for self registration, a block_coupon setting can be forced to enable auth_email while handling the signup.
Not the most elegant solution, I do agree, but it was added outside of my coding scope.
